---
# Source: oncall/templates/celery/deployment-celery.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-oncall-celery
  labels:
    helm.sh/chart: oncall-1.0.1
    app.kubernetes.io/name: oncall
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.0.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oncall
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: celery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oncall
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: celery
    spec:
      serviceAccountName: release-name-oncall
      securityContext:
        {}
      initContainers:        
        - name: wait-for-db
          image: "grafana/oncall:v1.0.3"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', "until (python manage.py migrate --check); do echo Waiting for database migrations; sleep 2; done"]
          env:
                    - name: BASE_URL
                      value: https://example.com
                    - name: SECRET_KEY
                      valueFrom:
                        secretKeyRef:
                          name: release-name-oncall
                          key: SECRET_KEY
                    - name: MIRAGE_SECRET_KEY
                      valueFrom:
                        secretKeyRef:
                          name: release-name-oncall
                          key: MIRAGE_SECRET_KEY
                    - name: MIRAGE_CIPHER_IV
                      value: "1234567890abcdef"
                    - name: DJANGO_SETTINGS_MODULE
                      value: "settings.helm"
                    - name: AMIXR_DJANGO_ADMIN_PATH
                      value: "admin"
                    - name: OSS
                      value: "True"
                    - name: UWSGI_LISTEN
                      value: "1024"
                    - name: MYSQL_HOST
                      value: release-name-mariadb
                    - name: MYSQL_PORT
                      value: "3306"
                    - name: MYSQL_DB_NAME
                      value: "oncall"
                    - name: MYSQL_USER
                      value: "root"
                    - name: MYSQL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: release-name-mariadb
                          key: mariadb-root-password
                    - name: RABBITMQ_USERNAME
                      value: "user"
                    - name: RABBITMQ_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: release-name-rabbitmq
                          key: rabbitmq-password
                    - name: RABBITMQ_HOST
                      value: release-name-rabbitmq
                    - name: RABBITMQ_PORT
                      value: "5672"
                    - name: REDIS_HOST
                      value: release-name-redis-master
                    - name: REDIS_PORT
                      value: "6379"
                    - name: REDIS_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: release-name-redis
                          key: redis-password
      containers:
        - name: oncall
          securityContext:
            {}
          image: "grafana/oncall:v1.0.3"
          command: ["./celery_with_exporter.sh"]
          imagePullPolicy: IfNotPresent
          env:
            - name: CELERY_WORKER_QUEUE
              value: "default,critical,long,slack,telegram,webhook,celery"
            - name: CELERY_WORKER_CONCURRENCY
              value: "1"
            - name: CELERY_WORKER_MAX_TASKS_PER_CHILD
              value: "100"
            - name: CELERY_WORKER_SHUTDOWN_INTERVAL
              value: "65m"
            - name: CELERY_WORKER_BEAT_ENABLED
              value: "True"
            - name: BASE_URL
              value: https://example.com
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-oncall
                  key: SECRET_KEY
            - name: MIRAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-oncall
                  key: MIRAGE_SECRET_KEY
            - name: MIRAGE_CIPHER_IV
              value: "1234567890abcdef"
            - name: DJANGO_SETTINGS_MODULE
              value: "settings.helm"
            - name: AMIXR_DJANGO_ADMIN_PATH
              value: "admin"
            - name: OSS
              value: "True"
            - name: UWSGI_LISTEN
              value: "1024"
            - name: MYSQL_HOST
              value: release-name-mariadb
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB_NAME
              value: "oncall"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-mariadb
                  key: mariadb-root-password
            - name: RABBITMQ_USERNAME
              value: "user"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-rabbitmq
                  key: rabbitmq-password
            - name: RABBITMQ_HOST
              value: release-name-rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: REDIS_HOST
              value: release-name-redis-master
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-redis
                  key: redis-password
          livenessProbe:
            exec:
              command: [
                "bash",
                "-c",
                "celery inspect ping -A engine -d celery@$HOSTNAME"
              ]
            initialDelaySeconds: 30
            periodSeconds: 300
            timeoutSeconds: 10
          resources:
            {}
