---
# Source: oncall/templates/engine/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-oncall-engine
  labels:
    helm.sh/chart: oncall-1.0.1
    app.kubernetes.io/name: oncall
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.0.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oncall
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: engine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oncall
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: engine
    spec:
      serviceAccountName: release-name-oncall
      securityContext:
        {}
      initContainers:        
        - name: wait-for-db
          image: "grafana/oncall:v1.0.3"
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', "until (python manage.py migrate --check); do echo Waiting for database migrations; sleep 2; done"]
          env:
                    - name: BASE_URL
                      value: https://example.com
                    - name: SECRET_KEY
                      valueFrom:
                        secretKeyRef:
                          name: release-name-oncall
                          key: SECRET_KEY
                    - name: MIRAGE_SECRET_KEY
                      valueFrom:
                        secretKeyRef:
                          name: release-name-oncall
                          key: MIRAGE_SECRET_KEY
                    - name: MIRAGE_CIPHER_IV
                      value: "1234567890abcdef"
                    - name: DJANGO_SETTINGS_MODULE
                      value: "settings.helm"
                    - name: AMIXR_DJANGO_ADMIN_PATH
                      value: "admin"
                    - name: OSS
                      value: "True"
                    - name: UWSGI_LISTEN
                      value: "1024"
                    - name: MYSQL_HOST
                      value: release-name-mariadb
                    - name: MYSQL_PORT
                      value: "3306"
                    - name: MYSQL_DB_NAME
                      value: "oncall"
                    - name: MYSQL_USER
                      value: "root"
                    - name: MYSQL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: release-name-mariadb
                          key: mariadb-root-password
                    - name: RABBITMQ_USERNAME
                      value: "user"
                    - name: RABBITMQ_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: release-name-rabbitmq
                          key: rabbitmq-password
                    - name: RABBITMQ_HOST
                      value: release-name-rabbitmq
                    - name: RABBITMQ_PORT
                      value: "5672"
                    - name: REDIS_HOST
                      value: release-name-redis-master
                    - name: REDIS_PORT
                      value: "6379"
                    - name: REDIS_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: release-name-redis
                          key: redis-password
      containers:
        - name: oncall
          securityContext:
            {}
          image: "grafana/oncall:v1.0.3"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: BASE_URL
              value: https://example.com
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-oncall
                  key: SECRET_KEY
            - name: MIRAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: release-name-oncall
                  key: MIRAGE_SECRET_KEY
            - name: MIRAGE_CIPHER_IV
              value: "1234567890abcdef"
            - name: DJANGO_SETTINGS_MODULE
              value: "settings.helm"
            - name: AMIXR_DJANGO_ADMIN_PATH
              value: "admin"
            - name: OSS
              value: "True"
            - name: UWSGI_LISTEN
              value: "1024"
            - name: MYSQL_HOST
              value: release-name-mariadb
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB_NAME
              value: "oncall"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-mariadb
                  key: mariadb-root-password
            - name: RABBITMQ_USERNAME
              value: "user"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-rabbitmq
                  key: rabbitmq-password
            - name: RABBITMQ_HOST
              value: release-name-rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: REDIS_HOST
              value: release-name-redis-master
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-redis
                  key: redis-password
          livenessProbe:
            httpGet:
              path: /health/
              port: http
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready/
              port: http
            periodSeconds: 60
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              path: /startupprobe/
              port: http
            periodSeconds: 60
            timeoutSeconds: 3
          resources:
            {}
